Add --no-clipboard option
Gustash/Hyprshot pull request #37
Opened 2024-03-09 21:03 UTC by Sryther

Add the possibility to avoid using clipboard copy.

2024-03-09 22:34 UTC, ProMix0 commented
Does it interfere with clipboard-only option? Maybe more general approach with kinda clipboard modes should be used?

2024-03-11 15:40 UTC, Sryther commented
Thanks for you feedback.
I changed the way clipboard options are supported to have only one: `--clipboard-mode` which accepts `always` (default), `no` and `only`.

2024-06-01 18:34 UTC, Gustash requested changes
I don't like the semantics of `--clipboard-mode`. I honestly think the user API should be `--clipboard-only` and `--no-clipboard`. Internally you can keep the `CLIPBOARD_MODE` variable, but change it to `on`, `off`, `only`.

2024-06-01 18:35 UTC, Gustash commented
Don't worry about which should take precedence over which. It's the user's fault if they provide both flags, they don't make sense together in the first place

2025-12-18 21:07 UTC, closed without merging