Add -D,--delay option to allow setting a delay after selecting an area to screenshot.
Gustash/Hyprshot pull request #56
Opened 2024-06-12 20:53 UTC by kraetzin

There are cases where something in the selected area/window has to be highlighted/hovered over with a mouse and window focus. The loss of focus during area/window selection means this can't be done. Adding a delay option means that the user has time to do this before a screenshot of the area is saved.

This pull request adds the `-D`/`--delay <time in seconds>` option to enable this. The delay takes place after selection, just before `save_geometry` is called.

2024-06-13 09:30 UTC, Gustash commented
Doesn't `--freeze` already address this issue?

2024-06-13 12:57 UTC, kraetzin commented
Ah I hadn't noticed `--freeze` required the `hyprpicker` dependency, so when I tried it didn't do anything, my bad. Trying out `--freeze` with hyprpicker installed, I can achieve a similar function to `--delay` by running `sleep <time> && hyprshot --freeze -m window`. Personally I find it more intuitive to use the delay function, but that's just how I've always done those sorts of screenshots under X11.

Feel free to close the PR if you feel `--delay` is redundant!

2024-06-13 13:42 UTC, Gustash commented
Why do you need a delay/sleep? You can just do whatever action you want, then call Hyprshot with freeze whenever what you want to screenshot is on screen. 

The screen won't change at all while you're frozen

2024-06-13 14:03 UTC, kraetzin commented
That works if using hotkeys to run the command, however often I'm calling hyprshot from the command line with a custom path, filename, or different mode to usual. In that case, the terminal has focus and I need time to switch window focus back after executing the command in the terminal.

2024-06-13 17:57 UTC, Gustash requested changes

2024-06-13 17:57 UTC, Gustash commented on hyprshot
> +  -D, --delay		    how long to delay taking the screenshot after selection
Change this to spaces instead of tabs, to match the others

2024-06-13 17:57 UTC, Gustash commented on hyprshot
> +  -D, --delay		    how long to delay taking the screenshot after selection
also, specify that the delay is in seconds

2024-06-13 17:57 UTC, Gustash commented on hyprshot
> +    sleep ${DELAY:-0}
Better to check if it's a number bigger than 0, and only call sleep if that is the case:

```suggestion
    if [ ${DELAY} -gt 0 ] 2>/dev/null; then
        sleep ${DELAY}
    fi
```

2024-06-16 20:42 UTC, Gustash approved these changes

2024-06-16 20:43 UTC, merged